version '3.7'

services:

	hub:
		image: selenium/hub:latest
		volumes:
		 - ./web/application:/application
		ports:
		 - "4444:4444"
		 
	chrome:
		image: selenium/node-chrome:latest
		depends_on: 
		  - hub
		evironment:
		- HUB_HOST=hub
		
	firefox:
		image: selenium/node-firefox:latest
		depends_on: 
		  - hub
		evironment:
		- HUB_HOST=hub